import { Instrument } from "../types/strategy";

const instruments: Instrument[] = [
    {
        id: '1',
        exchange: 'NSE',
        instrumentType: 'EQUITY',
        priceGrowth: 5,
        price: 100,
        marketCapRank: 7,
        avgDailyTransactionValue: 250000000,
    },
    {
        id: '2',
        exchange: 'NSE',
        instrumentType: 'EQUITY',
        priceGrowth: -2,
        price: 95,
        marketCapRank: 22,
        avgDailyTransactionValue: 400000000,
    },
    {
        id: '3',
        exchange: 'BSE',
        instrumentType: 'ETFs',
        priceGrowth: 3,
        price: 110,
        marketCapRank: 19,
        avgDailyTransactionValue: 350000000,
    },
    {
        id: '4',
        exchange: 'NYSE',
        instrumentType: 'EQUITY',
        priceGrowth: 13,
        price: 120,
        marketCapRank: 16,
        avgDailyTransactionValue: 500000000,
    },
    {
        id: '5',
        exchange: 'BSE',
        instrumentType: 'EQUITY',
        priceGrowth: 14,
        price: 186,
        marketCapRank: 24,
        avgDailyTransactionValue: 256000000,
    },
    {
        id: '6',
        exchange: 'NSE',
        instrumentType: 'EQUITY',
        priceGrowth: -2,
        price: 232,
        marketCapRank: 17,
        avgDailyTransactionValue: 350500000,
    },
    {
        id: '7',
        exchange: 'BSE',
        instrumentType: 'BOND',
        priceGrowth: 3,
        price: 101,
        marketCapRank: 1,
        avgDailyTransactionValue: 310000000,
    },
    {
        id: '8',
        exchange: 'NYSE',
        instrumentType: 'EQUITY',
        priceGrowth: 18,
        price: 165,
        marketCapRank: 13,
        avgDailyTransactionValue: 500000000,
    },
    {
        id: '9',
        exchange: 'NSE',
        instrumentType: 'BOND',
        priceGrowth: -5,
        price: 43,
        marketCapRank: 23,
        avgDailyTransactionValue: 750000000,
    },
    {
        id: '10',
        exchange: 'BSE',
        instrumentType: 'EQUITY',
        priceGrowth: -2,
        price: 95,
        marketCapRank: 10,
        avgDailyTransactionValue: 155000000,
    },
    {
        id: '11',
        exchange: 'NSE',
        instrumentType: 'ETFs',
        priceGrowth: 3,
        price: 65,
        marketCapRank: 20,
        avgDailyTransactionValue: 350560000,
    },
    {
        id: '12',
        exchange: 'NYSE',
        instrumentType: 'EQUITY',
        priceGrowth: 10,
        price: 120,
        marketCapRank: 12,
        avgDailyTransactionValue: 508000000,
    },
    {
        id: '13',
        exchange: 'NSE',
        instrumentType: 'EQUITY',
        priceGrowth: 21,
        price: 100,
        marketCapRank: 8,
        avgDailyTransactionValue: 605000000,
    },
    {
        id: '14',
        exchange: 'BSE',
        instrumentType: 'EQUITY',
        priceGrowth: -2,
        price: 95,
        marketCapRank: 14,
        avgDailyTransactionValue: 390000600,
    },
    {
        id: '15',
        exchange: 'BSE',
        instrumentType: 'ETFs',
        priceGrowth: 23,
        price: 143,
        marketCapRank: 15,
        avgDailyTransactionValue: 390000000,
    },
    {
        id: '16',
        exchange: 'NYSE',
        instrumentType: 'EQUITY',
        priceGrowth: 16,
        price: 12,
        marketCapRank: 4,
        avgDailyTransactionValue: 256000000,
    },
    {
        id: '17',
        exchange: 'NSE',
        instrumentType: 'EQUITY',
        priceGrowth: 19,
        price: 108,
        marketCapRank: 6,
        avgDailyTransactionValue: 280000000,
    },
    {
        id: '18',
        exchange: 'NSE',
        instrumentType: 'BOND',
        priceGrowth: -2,
        price: 9,
        marketCapRank: 18,
        avgDailyTransactionValue: 470000000,
    },
    {
        id: '19',
        exchange: 'NSE',
        instrumentType: 'EQUITY',
        priceGrowth: -13,
        price: 11,
        marketCapRank: 3,
        avgDailyTransactionValue: 300000000,
    },
    {
        id: '20',
        exchange: 'NYSE',
        instrumentType: 'BOND',
        priceGrowth: 13,
        price: 128,
        marketCapRank: 11,
        avgDailyTransactionValue: 200000000,
    },
    {
        id: '21',
        exchange: 'BSE',
        instrumentType: 'EQUITY',
        priceGrowth: 22,
        price: 167,
        marketCapRank: 21,
        avgDailyTransactionValue: 560000000,
    },
    {
        id: '22',
        exchange: 'NSE',
        instrumentType: 'EQUITY',
        priceGrowth: -2,
        price: 209,
        marketCapRank: 2,
        avgDailyTransactionValue: 670008000,
    },
    {
        id: '23',
        exchange: 'NSE',
        instrumentType: 'EQUITY',
        priceGrowth: 7,
        price: 110,
        marketCapRank: 9,
        avgDailyTransactionValue: 350000000,
    },
    {
        id: '24',
        exchange: 'NYSE',
        instrumentType: 'EQUITY',
        priceGrowth: 10,
        price: 10,
        marketCapRank: 5,
        avgDailyTransactionValue: 500000000,
    },
];

export { instruments }